<?php
function portfolio_edit_menu() {
    $items['basic_information'] = array(
     'title' => 'Portfolio Information',
     'description' => 'A page for entering basic portfolio information',
     'weight' => 0,
     'page callback' => 'basic_information',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );
    $items['new_portfolio'] = array(
     'title' => 'Create a new Portfolio',
     'description' => 'Users choose a portfolio type',
     'weight' => 0,
     'page callback' => 'new_portfolio',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );   
  return $items;
}

function new_portfolio() {
  return drupal_get_form("new_portfolio_form");
}

function new_portfolio_form() {
	$form['type'] = array(
	  '#type' => 'select', 
	  '#title' => t('Portfolio Type'), 
	  '#options' => array(
			 0 => t('Picture based Portfolio'),
			 1 => t('Text based Portfolio'),
		  ),
	  '#required' => TRUE,
	);
	$form['publish'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Create Portfolio'), 	
	);
	return $form;
}

function new_portfolio_form_submit($form, &$form_state) {
    global $user;
	$node = new stdClass();
	$node->title = 'new portfolio';
    $node->type         = 'portfolio';
	$node->language   = 'en';
	$node->uid = $user->uid;
	$node->created     = time();
	$node->changed    = $node->created;
	$node->status       = 1;         // Published?
	$node->promote    = 0;         // Display on front page?
	$node->sticky       = 0;          // Display top of page?
	$node->format      = 0;          // Filtered HTML?
	$node->revision     = 1;
	$node->log           = t('Node created: '.$node->title);
	
	$node->portfolio_type['und'][0]['value'] = $form_state['values']['type'];

	
	node_save($node);
	drupal_goto('basic_information/'.$node->nid);
}

function basic_information() {
  return drupal_get_form("basic_information_form");
}

function basic_information_form() {
 global $user;
 $form['url_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Website Address'),
      '#collapsible' => FALSE,
    );
	$form['url_settings']['url'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Website address'), 
	  '#prefix' => '<label id="www_domain_label">www.</label>', 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => TRUE,
	  '#suffix' => '<label id="url_domain_label">.example.com</label>',
	);
 $form['titles'] = array(
      '#type' => 'fieldset',
      '#title' => t('Portfolio Titles'),
      '#collapsible' => FALSE,
	  '#description' => 'These will be displayed at the top of your portfolio.',
    );
	$form['titles']['top_title'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Top Title'), 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => TRUE,
	);
	$form['titles']['bottom_title'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Bottom Title (optional)'), 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => FALSE,
	);
	 $form['footer_info'] = array(
		  '#type' => 'fieldset',
		  '#title' => t('Footer'),
		  '#collapsible' => FALSE,
		  '#description' => 'These will be displayed at the bottom of your portfolio.',
		);
	$form['footer_info']['footer'] = array(
		  '#type' => 'textarea', 
		  '#title' => t('Footer'), 
		  '#default_value' => $user->name.'\'s Awesome Portfolio from PortfolioMaker.com', 
		  '#required' => TRUE,
		);	
	$form['publish'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Create Portfolio'), 	
	);
	$path = drupal_get_path('module', 'portfolio');
	$form['#attached'] = array(
	  'css' => array (
	    'type' => 'file',
		'data' => $path . '/form_theme.css'
	  )
	);
	return $form;
}


function basic_information_form_submit($form, &$form_state) {
    $node = node_load(arg(1));
	$node->portfolio_header['und'][0]['value'] = $form_state['values']['top_title'];
	$node->portfolio_header_2['und'][0]['value'] = $form_state['values']['bottom_title'];
	$node->footer['und'][0]['value'] = $form_state['values']['footer'];
	$node->url['und'][0]['value'] = $form_state['values']['url'];
	$node->title = $node->portfolio_header['und'][0]['value']; //set the node title to the main header
	node_save($node);
	drupal_goto('node/'.$node->nid);
}
