<?php
function portfolio_edit_menu() {
    $items['basic_information'] = array(
     'title' => 'Portfolio Information',
     'description' => 'A page for entering basic portfolio information',
     'page callback' => 'basic_information',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );
    $items['new_portfolio'] = array(
     'title' => 'Create a new Portfolio',
     'description' => 'Users choose a portfolio type',
     'page callback' => 'new_portfolio',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );  
   $items['edit_portfolio'] = array(
     'title' => 'Edit your portfolio',
     'description' => '',
     'page callback' => 'edit_portfolio',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
   );     
  return $items;
}

function new_portfolio() {
  return drupal_get_form("new_portfolio_form");
}

function new_portfolio_form() {
	$form['type'] = array(
	  '#type' => 'select', 
	  '#title' => t('Portfolio Type'), 
	  '#options' => array(
			 0 => t('Picture based Portfolio'),
			 1 => t('Text based Portfolio'),
		  ),
	  '#required' => TRUE,
	);
	$form['publish'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Create Portfolio'), 	
	);
	return $form;
}

function new_portfolio_form_submit($form, &$form_state) {
    global $user;
	$node = new stdClass();
	$node->title = 'new portfolio';
    $node->type         = 'portfolio';
	$node->language   = 'en';
	$node->uid = $user->uid;
	$node->created     = time();
	$node->changed    = $node->created;
	$node->status       = 1;         // Published?
	$node->promote    = 0;         // Display on front page?
	$node->sticky       = 0;          // Display top of page?
	$node->format      = 0;          // Filtered HTML?
	$node->revision     = 1;
	$node->log           = t('Node created: '.$node->title);
	
	$node->portfolio_type['und'][0]['value'] = $form_state['values']['type'];

	
	node_save($node);
	drupal_goto('basic_information/'.$node->nid);
}

function basic_information() {
  return drupal_get_form("basic_information_form");
}

function basic_information_form() {
 global $user;
 $form['url_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Website Address'),
      '#collapsible' => FALSE,
    );
	$form['url_settings']['url'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Website address'), 
	  '#prefix' => '<label id="www_domain_label">www.</label>', 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => TRUE,
	  '#suffix' => '<label id="url_domain_label">.example.com</label>',
	);
 $form['titles'] = array(
      '#type' => 'fieldset',
      '#title' => t('Portfolio Titles'),
      '#collapsible' => FALSE,
	  '#description' => 'These will be displayed at the top of your portfolio.',
    );
	$form['titles']['top_title'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Top Title'), 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => TRUE,
	);
	$form['titles']['bottom_title'] = array(
	  '#type' => 'textfield', 
	  '#title' => t('Bottom Title (optional)'), 
	  '#size' => 60, 
	  '#maxlength' => 128, 
	  '#required' => FALSE,
	);
	 $form['footer_info'] = array(
		  '#type' => 'fieldset',
		  '#title' => t('Footer'),
		  '#collapsible' => FALSE,
		  '#description' => 'These will be displayed at the bottom of your portfolio.',
		);
	$form['footer_info']['footer'] = array(
		  '#type' => 'textarea', 
		  '#title' => t('Footer'), 
		  '#default_value' => $user->name.'\'s Awesome Portfolio from PortfolioMaker.com', 
		  '#required' => TRUE,
		);	
	$form['publish'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Create Portfolio'), 	
	);
	$path = drupal_get_path('module', 'portfolio_edit');
	$form['#attached'] = array(
	  'css' => array (
	    'type' => 'file',
		'data' => $path . '/form_theme.css'
	  )
	);
	return $form;
}


function basic_information_form_submit($form, &$form_state) {
    $node = node_load(arg(1));
	$node->portfolio_header['und'][0]['value'] = $form_state['values']['top_title'];
	$node->portfolio_header_2['und'][0]['value'] = $form_state['values']['bottom_title'];
	$node->footer['und'][0]['value'] = $form_state['values']['footer'];
	$node->url['und'][0]['value'] = $form_state['values']['url'];
	$node->title = $node->portfolio_header['und'][0]['value']; //set the node title to the main header
	node_save($node);
	drupal_goto('edit_portfolio/'.$node->nid.'/pages');
}

function edit_portfolio(){
    global $user;
	$node = node_load(arg(1));
	$form_state['build_info']['args'] = array($node);
	form_load_include($form_state, 'inc', 'node', 'node.pages');
	return drupal_build_form('portfolio_node_form', $form_state);
}

function portfolio_edit_form_alter(&$form, $form_state, $form_id) {

	if ($form_id == "portfolio_node_form" && arg(0) == 'edit_portfolio') { //hide everything!
		//$node = node_load(arg(1));
	    hide($form['url']);
	    hide($form['path']);
	    hide($form['title']);
		hide($form['pages']);
	    hide($form['portfolio_header']);
	    hide($form['portfolio_header_2']);
		hide($form['footer']);
		hide($form['portfolio_type']);
		hide($form['additional_settings']);
		$form['actions']['preview']['#access'] = FALSE;
		$form['actions']['delete']['#access'] = FALSE;
		
		drupal_set_message($form_id);
	
	if (arg(2) == "pages") {
	    show($form['pages']);
		drupal_set_title("Add and Edit Pages in your Portfolio");
		}
	if (arg(2) == "information") {
	    show($form['portfolio_header']);
	    show($form['portfolio_header_2']);
		show($form['footer']);
		drupal_set_title("Customize the Header and Footer of your Portfolio");
		}
/*	if (arg(2) == "colors") {
	    show($form['field_portfolio_colors']);
		drupal_set_title("Style your Portfolio!");
	} */
	//add cancel button
	  $form['actions']['cancel'] = array(
	  '#type' => 'submit', 
	  '#value' => t('Cancel'), 	
	  '#weight' => -100,
      '#submit' => array('cancel_edits'),
	);
	/*$form['pass_nid'] = array(
	'#type' => 'hidden',
	'#default_value' => $node->nid,
	'#weight' => -100,
	);*/
	}
}